### ISSUE TITLE
Which cloud resource would you expect to be supported by provider alibaba?

### ISSUE THREAD

**Issue by zzxwill** [crossplane/provider-alibaba#67]
We are currently implementing Alibaba Cloud OSS (#59 ), SLS project (#58 ) resources, and we are going to support more. 

We are looking forward to your feedback on the cloud resources you want most. 

Cloud resources implementation status:

- [x] ApsaraDB RDS
   - [x] PostgreSQL/Mysql
   - [x] Redis #88  @xiqiu618 @zzxwill 
- [x] SLS
   - [x] SLS Project: #58 
   - [x] SLS Logstore:  #77
   - [x] SLS Logtail 
- [x] OSS Bucket: Done. #59  @zzxwill 
- [ ] MQ: pending.
- [x] NAS
   - [x] FileSystem: #79 @zzxwill 
   - [x] MountTarget: #80 @zzxwill 
- [x] SLB
  - [x] CLB: #84  Update is not yet supported.

**Comment by Dkaykay** [comment]
First of all, thanks for your work!
  
Currently, me and my team are mainly relying on postgresql db and redis cache on hyperscalers az, aws, gcp and alicloud, so it would help us a lot if you would start with:

1. ApsaraDB RDS for PostgreSQL
2. ApsaraDB for Redis

Best, 
D

**Comment by zzxwill** [comment]
@Dkaykay Much appreciated for your feedback. This is essential to the development prioritys. Thanks.

**Comment by lowkeyrd** [comment]
Redis and MQ are general requirements, and I will collect more requirements

**Comment by xiqiu618** [comment]
@zzxwill I would like to try implementing Alibaba Cloud  Redis
https://help.aliyun.com/product/26340.html?spm=a2c4g.11186623.6.540.13612846iopvp9

**Comment by zzxwill** [comment]
> @zzxwill I would like to try implementing Alibaba Cloud Redis
> https://help.aliyun.com/product/26340.html?spm=a2c4g.11186623.6.540.13612846iopvp9

Great, thanks. Please go head

**Comment by zzxwill** [comment]
Kafaka is added to the wish list per #74

**Comment by yangsoon** [comment]
Thanks for your work!

Now we need `provider-alibaba` to implementing SLS `logstore`

**Comment by zzxwill** [comment]
Please help reopen this tracking issue.

**Comment by yangsoon** [comment]
I hope provider-alibaba can add more configuration features for SLS.

I want use `logtail` to collect my container's logs through the method described by https://www.alibabacloud.com/help/doc-detail/157315.htm?spm=a2c63.p38356.b99.91.4f8d27caGBSuxZ

I wish I can use `provider-alibaba` to:

1.  create Logtail configuration files
2. create Index for logstore
3. create MachineGroup
4. apply Logtail configuration to MachineGroup

**Comment by znqerz** [comment]
Hope the provider can also support to create managed kubernetes and related cloud resource on AliCloud.

**Comment by zzxwill** [comment]
> Hope the provider can also support to create managed kubernetes and related cloud resource on AliCloud.

Noted. Do you intend to manage multiple Kubernetes clusters?

**Comment by scarlet25151** [comment]
Hi, thanks for your work!
Now me and my teammate need support of `elasticIP` implementation for building OAM application base on the Alicloud cloud resource.

**Comment by eperezvcc** [comment]
> > Hope the provider can also support to create managed kubernetes and related cloud resource on AliCloud.
> 
> Noted. Do you intend to manage multiple Kubernetes clusters?

I definitely will manage multiple Kubernetes clusters :)

**Comment by zzxwill** [comment]
> > > Hope the provider can also support to create managed kubernetes and related cloud resource on AliCloud.
> > 
> > 
> > Noted. Do you intend to manage multiple Kubernetes clusters?
> 
> I definitely will manage multiple Kubernetes clusters :)

Sure. Besides ACK managed Kubernetes, which cloud resources do you need?

**Comment by Maple1401** [comment]
Why are there no  ECS resources
